# Generated by Django 4.1.1 on 2022-09-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('dob', models.CharField(max_length=60)),
                ('mobile', models.IntegerField()),
                ('gender', models.CharField(max_length=40)),
            ],
        ),
    ]
